services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped

    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80

    ports:
      - "80:80"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.lab`)
      - traefik.http.routers.dashboard.entrypoints=web
      - traefik.http.routers.dashboard.service=api@internal

    networks:
      - proxy

networks:
  proxy:
    external: true